# Generated by Django 5.1 on 2025-06-20 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Year must be in YYYY-YYYY format (e.g., 2020-2023)', regex='^\\d{4}-\\d{4}$')])),
                ('degree', models.CharField(default='N/A', max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('CGPA_Marks', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='prof.userprofile')),
            ],
        ),
    ]
