# Generated by Django 5.1 on 2025-06-21 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(help_text='Enter a value between 1 and 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myskills', to='prof.userprofile')),
            ],
        ),
    ]
