# Generated by Django 5.1 on 2025-06-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_myskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
