# Generated by Django 5.1 on 2025-06-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='CGPA_Marks',
            new_name='cgpa_marks',
        ),
    ]
