# Generated by Django 5.1 on 2025-06-20 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_rename_cgpa_marks_education_cgpa_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Year must be in YYYY-YYYY format (e.g., 2020-2023)', regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
