# Generated by Django 5.1 on 2025-06-20 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_alter_education_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Year must be in YYYY-YYYY format (e.g., 2020-2023)', regex='^\\d{4}-\\d{4}$')])),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('tech_details', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='prof.userprofile')),
            ],
        ),
    ]
